### ISSUE TITLE
does not run in docker (microsoft/dotnet/)

### ISSUE THREAD

**Issue by Oppodelldog** [cmksoftdev/AnimatedPngCreator#14]
I tried to run **AnimatedPngCreator.Console** using the official docker image, but got an error:

> /usr/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/nils/Projects/AnimatedPngCreator/AnimatedPngCreator.Console/AnimatedPngCreator.Console.csproj]
The build failed. Please fix the build errors and run again.

The docker run call:
```shell
~/Projects/AnimatedPngCreator/AnimatedPngCreator.Console$ docker run --rm -it -w $(pwd) -v $(pwd):$(pwd) microsoft/dotnet dotnet run
```

Maybe you can set the proper version in the project config to run in dotnet core?

**Comment by cmk1988** [comment]
Hi @Oppodelldog ,
thanks for your posting and your interest in AnimatedPngCreator. We will investigate your issue and after that we will letting you know what we decided to do.
Greetings, Chris

**Comment by cmk1988** [comment]
@Seegurke13 Gibt's hier neues zu?
